using SGLNet.Maths;
using System.Runtime.InteropServices;

namespace SGLNet
{
    public class PackedColour : CustomValueType<PackedColour, uint>
    {
        private PackedColour(uint value) : base(value) { }
        public static implicit operator PackedColour(uint value) { return new PackedColour(value); }
        public static implicit operator PackedColour(int value) { return new PackedColour((uint)value); }
        public static implicit operator uint(PackedColour custom) { return custom._value; }
        public static implicit operator int(PackedColour custom) { return (int)custom._value; }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Colour
    {
        private float r;
        private float g;
        private float b;
        private float a;

        public float R
        {
            readonly get => r;
            set => r = value;
        }

        public float G
        {
            readonly get => g;
            set => g = value;
        }

        public float B
        {
            readonly get => b;
            set => b = value;
        }

        public float A
        {
            readonly get => a;
            set => a = value;
        }

        public PackedColour Packed
        {
            readonly get
            {
                byte rb = (byte)(r * 255f);
                byte gb = (byte)(g * 255f);
                byte bb = (byte)(b * 255f);
                byte ab = (byte)(a * 255f);

                return (uint)((ab << 24) | (rb << 16) | (gb << 8) | bb);
            }
            set
            {
                byte a8 = (byte)((value >> 24) & 0xFF);
                byte r8 = (byte)((value >> 16) & 0xFF);
                byte g8 = (byte)((value >> 8) & 0xFF);
                byte b8 = (byte)(value & 0xFF);

                r = r8 / 255f;
                g = g8 / 255f;
                b = b8 / 255f;
                a = a8 / 255f;
            }
        }

        public static implicit operator Vec3(in Colour c) =>
            c.ToVec3();

        public static implicit operator Vec4(in Colour c) =>
            c.ToVec4();

        public static implicit operator Colour(in Vec3 v) =>
            new(v.X, v.Y, v.Z);

        public static implicit operator Colour(in Vec4 v) =>
            new(v.X, v.Y, v.Z, v.W);

        public readonly Vec3 ToVec3() =>
            new(r, g, b);

        public readonly Vec4 ToVec4() =>
            new(r, g, b, a);

        public Colour()
        {
            r = g = b = 0f;
            a = 1f;
        }

        public Colour(PackedColour packed) =>
            Packed = packed;

        public Colour(float r, float g, float b, float a = 1f)
        {
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }

        public Colour(byte r, byte g, byte b, byte a = 255)
        {
            this.r = r / 255f;
            this.g = g / 255f;
            this.b = b / 255f;
            this.a = a / 255f;
        }

        // Autogenerated by `ColourGenerator.py`
        public static Colour AliceBlue => new(0xF0F8FF);
        public static Colour AntiqueWhite => new(0xFAEBD7);
        public static Colour Aqua => new(0x00FFFF);
        public static Colour Aquamarine => new(0x7FFFD4);
        public static Colour Azure => new(0xF0FFFF);
        public static Colour Beige => new(0xF5F5DC);
        public static Colour Bisque => new(0xFFE4C4);
        public static Colour Black => new(0x000000);
        public static Colour BlanchedAlmond => new(0xFFEBCD);
        public static Colour Blue => new(0x0000FF);
        public static Colour BlueViolet => new(0x8A2BE2);
        public static Colour Brown => new(0xA52A2A);
        public static Colour BurlyWood => new(0xDEB887);
        public static Colour CadetBlue => new(0x5F9EA0);
        public static Colour Chartreuse => new(0x7FFF00);
        public static Colour Chocolate => new(0xD2691E);
        public static Colour Coral => new(0xFF7F50);
        public static Colour CornflowerBlue => new(0x6495ED);
        public static Colour Cornsilk => new(0xFFF8DC);
        public static Colour Crimson => new(0xDC143C);
        public static Colour Cyan => new(0x00FFFF);
        public static Colour DarkBlue => new(0x00008B);
        public static Colour DarkCyan => new(0x008B8B);
        public static Colour DarkGoldenRod => new(0xB8860B);
        public static Colour DarkGray => new(0xA9A9A9);
        public static Colour DarkGreen => new(0x006400);
        public static Colour DarkKhaki => new(0xBDB76B);
        public static Colour DarkMagenta => new(0x8B008B);
        public static Colour DarkOliveGreen => new(0x556B2F);
        public static Colour DarkOrange => new(0xFF8C00);
        public static Colour DarkOrchid => new(0x9932CC);
        public static Colour DarkRed => new(0x8B0000);
        public static Colour DarkSalmon => new(0xE9967A);
        public static Colour DarkSeaGreen => new(0x8FBC8F);
        public static Colour DarkSlateBlue => new(0x483D8B);
        public static Colour DarkSlateGray => new(0x2F4F4F);
        public static Colour DarkTurquoise => new(0x00CED1);
        public static Colour DarkViolet => new(0x9400D3);
        public static Colour DeepPink => new(0xFF1493);
        public static Colour DeepSkyBlue => new(0x00BFFF);
        public static Colour DimGray => new(0x696969);
        public static Colour DodgerBlue => new(0x1E90FF);
        public static Colour FireBrick => new(0xB22222);
        public static Colour FloralWhite => new(0xFFFAF0);
        public static Colour ForestGreen => new(0x228B22);
        public static Colour Fuchsia => new(0xFF00FF);
        public static Colour Gainsboro => new(0xDCDCDC);
        public static Colour GhostWhite => new(0xF8F8FF);
        public static Colour Gold => new(0xFFD700);
        public static Colour GoldenRod => new(0xDAA520);
        public static Colour Gray => new(0x808080);
        public static Colour Green => new(0x008000);
        public static Colour GreenYellow => new(0xADFF2F);
        public static Colour HoneyDew => new(0xF0FFF0);
        public static Colour HotPink => new(0xFF69B4);
        public static Colour IndianRed => new(0xCD5C5C);
        public static Colour Indigo => new(0x4B0082);
        public static Colour Ivory => new(0xFFFFF0);
        public static Colour Khaki => new(0xF0E68C);
        public static Colour Lavender => new(0xE6E6FA);
        public static Colour LavenderBlush => new(0xFFF0F5);
        public static Colour LawnGreen => new(0x7CFC00);
        public static Colour LemonChiffon => new(0xFFFACD);
        public static Colour LightBlue => new(0xADD8E6);
        public static Colour LightCoral => new(0xF08080);
        public static Colour LightCyan => new(0xE0FFFF);
        public static Colour LightGoldenRodYellow => new(0xFAFAD2);
        public static Colour LightGray => new(0xD3D3D3);
        public static Colour LightGreen => new(0x90EE90);
        public static Colour LightPink => new(0xFFB6C1);
        public static Colour LightSalmon => new(0xFFA07A);
        public static Colour LightSeaGreen => new(0x20B2AA);
        public static Colour LightSkyBlue => new(0x87CEFA);
        public static Colour LightSlateGray => new(0x778899);
        public static Colour LightSteelBlue => new(0xB0C4DE);
        public static Colour LightYellow => new(0xFFFFE0);
        public static Colour Lime => new(0x00FF00);
        public static Colour LimeGreen => new(0x32CD32);
        public static Colour Linen => new(0xFAF0E6);
        public static Colour Magenta => new(0xFF00FF);
        public static Colour Maroon => new(0x800000);
        public static Colour MediumAquaMarine => new(0x66CDAA);
        public static Colour MediumBlue => new(0x0000CD);
        public static Colour MediumOrchid => new(0xBA55D3);
        public static Colour MediumPurple => new(0x9370DB);
        public static Colour MediumSeaGreen => new(0x3CB371);
        public static Colour MediumSlateBlue => new(0x7B68EE);
        public static Colour MediumSpringGreen => new(0x00FA9A);
        public static Colour MediumTurquoise => new(0x48D1CC);
        public static Colour MediumVioletRed => new(0xC71585);
        public static Colour MidnightBlue => new(0x191970);
        public static Colour MintCream => new(0xF5FFFA);
        public static Colour MistyRose => new(0xFFE4E1);
        public static Colour Moccasin => new(0xFFE4B5);
        public static Colour NavajoWhite => new(0xFFDEAD);
        public static Colour Navy => new(0x000080);
        public static Colour OldLace => new(0xFDF5E6);
        public static Colour Olive => new(0x808000);
        public static Colour OliveDrab => new(0x6B8E23);
        public static Colour Orange => new(0xFFA500);
        public static Colour OrangeRed => new(0xFF4500);
        public static Colour Orchid => new(0xDA70D6);
        public static Colour PaleGoldenRod => new(0xEEE8AA);
        public static Colour PaleGreen => new(0x98FB98);
        public static Colour PaleTurquoise => new(0xAFEEEE);
        public static Colour PaleVioletRed => new(0xDB7093);
        public static Colour PapayaWhip => new(0xFFEFD5);
        public static Colour PeachPuff => new(0xFFDAB9);
        public static Colour Peru => new(0xCD853F);
        public static Colour Pink => new(0xFFC0CB);
        public static Colour Plum => new(0xDDA0DD);
        public static Colour PowderBlue => new(0xB0E0E6);
        public static Colour Purple => new(0x800080);
        public static Colour RebeccaPurple => new(0x663399);
        public static Colour Red => new(0xFF0000);
        public static Colour RosyBrown => new(0xBC8F8F);
        public static Colour RoyalBlue => new(0x4169E1);
        public static Colour SaddleBrown => new(0x8B4513);
        public static Colour Salmon => new(0xFA8072);
        public static Colour SandyBrown => new(0xF4A460);
        public static Colour SeaGreen => new(0x2E8B57);
        public static Colour SeaShell => new(0xFFF5EE);
        public static Colour Sienna => new(0xA0522D);
        public static Colour Silver => new(0xC0C0C0);
        public static Colour SkyBlue => new(0x87CEEB);
        public static Colour SlateBlue => new(0x6A5ACD);
        public static Colour SlateGray => new(0x708090);
        public static Colour Snow => new(0xFFFAFA);
        public static Colour SpringGreen => new(0x00FF7F);
        public static Colour SteelBlue => new(0x4682B4);
        public static Colour Tan => new(0xD2B48C);
        public static Colour Teal => new(0x008080);
        public static Colour Thistle => new(0xD8BFD8);
        public static Colour Tomato => new(0xFF6347);
        public static Colour Transparent => new(0x00000000);
        public static Colour Turquoise => new(0x40E0D0);
        public static Colour Violet => new(0xEE82EE);
        public static Colour Wheat => new(0xF5DEB3);
        public static Colour White => new(0xFFFFFF);
        public static Colour WhiteSmoke => new(0xF5F5F5);
        public static Colour Yellow => new(0xFFFF00);
        public static Colour YellowGreen => new(0x9ACD3);
    }
}